### ISSUE TITLE
Minor issue: multiple selector format

### ISSUE THREAD

**Issue by Rodrigap** [TrevorD6/prj-rev-bwfs-dasmoto#2]
https://github.com/TrevorD6/prj-rev-bwfs-dasmoto/blob/d856c36c588833f657d1773109a90c157781ce48/Dasmoto/resources/css/style.css#L1-L6

When you use multiple selectors, it's more common to put all the tags on one line! Like this:

h1, h2, h3, p {
  font-family: helvetica;
}

**Comment by TrevorD6** [comment]
Thanks.  That's what I would have thought, but all the examples in the lessons have them on separate lines.  I'll keep them on one line in the future.
