### ISSUE TITLE
Grade: Meets Expectations

### ISSUE THREAD

**Issue by Rodrigap** [TrevorD6/prj-rev-bwfs-dasmoto#4]
Great job with this project! Your HTML and CSS are both really clean, and your finished product looks just like the spec. Especially on a project like this, where the requirements are fairly small and you clearly have a good handle on the material, feel free to get creative and add additional styling and fonts and colors! Also, check out CSS animations if you've never seen them before! They can be really simple ways to set your work apart. There's a lot of online inspiration: https://www.webdesignerdepot.com/2014/05/8-simple-css3-transitions-that-will-wow-your-users/

Great job!

**Comment by TrevorD6** [comment]
Great, thanks.
